steps:
- name: "gcr.io/cloud-builders/go"
  args: ["build", "-tags","node","main.go"]
  env: [
    "GOARCH=amd64",
    "GOOS=linux",
    "CGO_ENABLED=0",
    "GOPATH=/workspace"
  ]
- name: "gcr.io/cloud-builders/npm"
  args: ["install", "--ignore-scripts", "-save", "local_modules/execer"]
- name: "gcr.io/cloud-builders/gcloud"
  args: [
    "beta",
    "functions",
    "deploy","${_NAME}",
    "--entry-point","${_ENTRY_POINT}",
    "--source","./",
    "--trigger-http",
    "--project","${PROJECT_ID}"
  ]